version: '3.8'

services:
  api:
    build: .
    container_name: aws-spot-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      # Credenciais para a API (opcional - você pode usar variáveis de ambiente ou um .env)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      # Mapear apenas para desenvolvimento (comentar em produção)
      #- ./:/app
      # Excluir node_modules do volume para usar a versão dentro do container
      - /app/node_modules
    restart: unless-stopped

  # Opcionalmente, você pode adicionar um servidor web para servir os arquivos estáticos
  nginx:
    image: nginx:alpine
    container_name: aws-spot-nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: unless-stopped